
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef ANYID_CANOPEN_SLAVE_H
#define ANYID_CANOPEN_SLAVE_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 AnyId_Canopen_Slave_valueRangeTest (UNS8 typeValue, void * value);
const indextable * AnyId_Canopen_Slave_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks);

/* Master node data struct */
extern CO_Data AnyId_Canopen_Slave_Data;
extern UNS64 uid;		/* Mapped at index 0x2000, subindex 0x00*/
extern UNS8 keyValue;		/* Mapped at index 0x2001, subindex 0x00*/
extern UNS8 addrValue;		/* Mapped at index 0x2002, subindex 0x00*/

#endif // ANYID_CANOPEN_SLAVE_H
