
/* File generated by gen_cfile.py. Should not be modified. */

#include "AnyId_Canopen_Client.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/
UNS64 Uid = 0x0;		/* Mapped at index 0x2000, subindex 0x00 */
UNS8 KeyValue = 0x0;		/* Mapped at index 0x2001, subindex 0x00 */
UNS8 AddValue = 0x0;		/* Mapped at index 0x2002, subindex 0x00 */

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 AnyId_Canopen_Client_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 AnyId_Canopen_Client_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 AnyId_Canopen_Client_iam_a_slave = 1;

TIMER_HANDLE AnyId_Canopen_Client_heartBeatTimers[1] = {TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 AnyId_Canopen_Client_obj1000 = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 AnyId_Canopen_Client_obj1001 = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t AnyId_Canopen_Client_Index1003_callbacks[] = 
                     {
                       NULL,
                       NULL,
                     };
                    subindex AnyId_Canopen_Client_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 AnyId_Canopen_Client_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 AnyId_Canopen_Client_obj1006 = 0x0;   /* 0 */

/* index 0x1008 :   Manufacturer Device Name. */
                    UNS8 AnyId_Canopen_Client_obj1008[10] = (UNS8*)"";
                    subindex AnyId_Canopen_Client_Index1008[] = 
                     {
                       { RO, visible_string, 10, (void*)&AnyId_Canopen_Client_obj1008 }
                     };

/* index 0x1009 :   Manufacturer Hardware Version. */
                    UNS8 AnyId_Canopen_Client_obj1009[10] = (UNS8*)"";
                    subindex AnyId_Canopen_Client_Index1009[] = 
                     {
                       { RO, visible_string, 10, (void*)&AnyId_Canopen_Client_obj1009 }
                     };

/* index 0x100A :   Manufacturer Software Version. */
                    UNS8 AnyId_Canopen_Client_obj100A[10] = (UNS8*)"";
                    subindex AnyId_Canopen_Client_Index100A[] = 
                     {
                       { RO, visible_string, 10, (void*)&AnyId_Canopen_Client_obj100A }
                     };

/* index 0x100C :   Guard Time */ 
                    UNS16 AnyId_Canopen_Client_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 AnyId_Canopen_Client_obj100D = 0x0;   /* 0 */

/* index 0x1011 :   Restore Default Parameters. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1011 = 127; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_All_Default_Parameters = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Communication_Default_Parameters = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Application_Default_Parameters = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_2 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_3 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_4 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_5 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_6 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_7 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_8 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_9 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_10 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_11 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_12 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_13 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_14 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_15 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_16 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_17 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_18 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_19 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_20 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_21 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_22 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_23 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_24 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_25 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_26 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_27 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_28 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_29 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_30 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_31 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_32 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_33 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_34 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_35 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_36 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_37 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_38 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_39 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_40 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_41 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_42 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_43 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_44 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_45 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_46 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_47 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_48 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_49 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_50 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_51 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_52 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_53 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_54 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_55 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_56 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_57 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_58 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_59 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_60 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_61 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_62 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_63 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_64 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_65 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_66 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_67 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_68 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_69 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_70 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_71 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_72 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_73 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_74 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_75 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_76 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_77 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_78 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_79 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_80 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_81 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_82 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_83 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_84 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_85 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_86 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_87 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_88 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_89 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_90 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_91 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_92 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_93 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_94 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_95 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_96 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_97 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_98 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_99 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_100 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_101 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_102 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_103 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_104 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_105 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_106 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_107 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_108 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_109 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_110 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_111 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_112 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_113 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_114 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_115 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_116 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_117 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_118 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_119 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_120 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_121 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_122 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_123 = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_124 = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1011[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1011 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_All_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Communication_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Application_Default_Parameters },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_1 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_2 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_3 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_4 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_5 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_6 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_7 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_8 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_9 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_10 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_11 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_12 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_13 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_14 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_15 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_16 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_17 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_18 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_19 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_20 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_21 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_22 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_23 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_24 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_25 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_26 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_27 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_28 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_29 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_30 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_31 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_32 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_33 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_34 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_35 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_36 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_37 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_38 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_39 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_40 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_41 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_42 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_43 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_44 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_45 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_46 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_47 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_48 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_49 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_50 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_51 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_52 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_53 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_54 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_55 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_56 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_57 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_58 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_59 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_60 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_61 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_62 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_63 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_64 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_65 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_66 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_67 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_68 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_69 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_70 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_71 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_72 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_73 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_74 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_75 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_76 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_77 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_78 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_79 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_80 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_81 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_82 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_83 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_84 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_85 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_86 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_87 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_88 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_89 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_90 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_91 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_92 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_93 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_94 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_95 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_96 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_97 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_98 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_99 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_100 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_101 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_102 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_103 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_104 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_105 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_106 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_107 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_108 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_109 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_110 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_111 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_112 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_113 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_114 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_115 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_116 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_117 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_118 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_119 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_120 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_121 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_122 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_123 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1011_Restore_Manufacturer_Defined_Default_Parameters_124 }
                     };

/* index 0x1012 :   TIME COB ID. */
                    UNS32 AnyId_Canopen_Client_obj1012 = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1012[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1012 }
                     };

/* index 0x1013 :   High Resolution Timestamp. */
                    UNS32 AnyId_Canopen_Client_obj1013 = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1013[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1013 }
                     };

/* index 0x1014 :   Emergency COB ID. */
                    UNS32 AnyId_Canopen_Client_obj1014 = 0x80;	/* 128 */
                    subindex AnyId_Canopen_Client_Index1014[] = 
                     {
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1014 }
                     };

/* index 0x1015 :   Inhibit Time Emergency. */
                    UNS16 AnyId_Canopen_Client_obj1015 = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1015[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1015 }
                     };

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1016 = 1; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1016[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex AnyId_Canopen_Client_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1016 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1016[0] }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 AnyId_Canopen_Client_obj1017 = 0x0;	/* 0 */
                    ODCallback_t AnyId_Canopen_Client_Index1017_callbacks[] = 
                     {
                       NULL,
                     };
                    subindex AnyId_Canopen_Client_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 AnyId_Canopen_Client_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1018 },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1018_Vendor_ID },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x600;	/* 1536 */
                    UNS32 AnyId_Canopen_Client_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x580;	/* 1408 */
                    subindex AnyId_Canopen_Client_Index1200[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1280 :   Client SDO 1 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1280 = 3; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1280_COB_ID_Client_to_Server_Transmit_SDO = 0x601;	/* 1537 */
                    UNS32 AnyId_Canopen_Client_obj1280_COB_ID_Server_to_Client_Receive_SDO = 0x581;	/* 1409 */
                    UNS8 AnyId_Canopen_Client_obj1280_Node_ID_of_the_SDO_Server = 0x1;	/* 1 */
                    subindex AnyId_Canopen_Client_Index1280[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1280 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1280_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1280_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1280_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1281 :   Client SDO 2 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1281 = 3; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1281_COB_ID_Client_to_Server_Transmit_SDO = 0x602;	/* 1538 */
                    UNS32 AnyId_Canopen_Client_obj1281_COB_ID_Server_to_Client_Receive_SDO = 0x582;	/* 1410 */
                    UNS8 AnyId_Canopen_Client_obj1281_Node_ID_of_the_SDO_Server = 0x2;	/* 2 */
                    subindex AnyId_Canopen_Client_Index1281[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1281 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1281_COB_ID_Client_to_Server_Transmit_SDO },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1281_COB_ID_Server_to_Client_Receive_SDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1281_Node_ID_of_the_SDO_Server }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1400 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1400_COB_ID_used_by_PDO = 0x200;	/* 512 */
                    UNS8 AnyId_Canopen_Client_obj1400_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1400_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1400_SYNC_start_value = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1400[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1400_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1400_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1400_SYNC_start_value }
                     };

/* index 0x1401 :   Receive PDO 2 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1401 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1401_COB_ID_used_by_PDO = 0x300;	/* 768 */
                    UNS8 AnyId_Canopen_Client_obj1401_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1401_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1401_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1401_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1401_SYNC_start_value = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1401[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1401 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1401_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1401_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1401_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1401_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1401_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1401_SYNC_start_value }
                     };

/* index 0x1402 :   Receive PDO 3 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1402 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1402_COB_ID_used_by_PDO = 0x400;	/* 1024 */
                    UNS8 AnyId_Canopen_Client_obj1402_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1402_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1402_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1402_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1402_SYNC_start_value = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1402[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1402 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1402_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1402_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1402_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1402_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1402_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1402_SYNC_start_value }
                     };

/* index 0x1403 :   Receive PDO 4 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1403 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1403_COB_ID_used_by_PDO = 0x500;	/* 1280 */
                    UNS8 AnyId_Canopen_Client_obj1403_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1403_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1403_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1403_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1403_SYNC_start_value = 0x0;	/* 0 */
                    subindex AnyId_Canopen_Client_Index1403[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1403 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1403_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1403_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1403_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1403_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1403_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1403_SYNC_start_value }
                     };

/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1600[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_Canopen_Client_Index1600[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1600[7] }
                     };

/* index 0x1601 :   Receive PDO 2 Mapping. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1601 = 8; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1601[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_Canopen_Client_Index1601[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1601 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1601[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1601[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1601[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1601[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1601[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1601[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1601[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1601[7] }
                     };

/* index 0x1602 :   Receive PDO 3 Mapping. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1602 = 8; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1602[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_Canopen_Client_Index1602[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1602 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1602[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1602[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1602[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1602[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1602[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1602[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1602[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1602[7] }
                     };

/* index 0x1603 :   Receive PDO 4 Mapping. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1603 = 8; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1603[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_Canopen_Client_Index1603[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1603 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1603[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1603[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1603[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1603[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1603[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1603[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1603[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1603[7] }
                     };

/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1800 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1800_COB_ID_used_by_PDO = 0x180;	/* 384 */
                    UNS8 AnyId_Canopen_Client_obj1800_Transmission_Type = 0x1;	/* 1 */
                    UNS16 AnyId_Canopen_Client_obj1800_Inhibit_Time = 0xC8;	/* 200 */
                    UNS8 AnyId_Canopen_Client_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1800_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1800_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t AnyId_Canopen_Client_Index1800_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_Canopen_Client_Index1800[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1800_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1800_SYNC_start_value }
                     };

/* index 0x1801 :   Transmit PDO 2 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1801 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1801_COB_ID_used_by_PDO = 0x280;	/* 640 */
                    UNS8 AnyId_Canopen_Client_obj1801_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1801_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1801_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1801_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1801_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t AnyId_Canopen_Client_Index1801_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_Canopen_Client_Index1801[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1801 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1801_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1801_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1801_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1801_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1801_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1801_SYNC_start_value }
                     };

/* index 0x1802 :   Transmit PDO 3 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1802 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1802_COB_ID_used_by_PDO = 0x380;	/* 896 */
                    UNS8 AnyId_Canopen_Client_obj1802_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1802_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1802_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1802_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1802_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t AnyId_Canopen_Client_Index1802_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_Canopen_Client_Index1802[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1802 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1802_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1802_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1802_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1802_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1802_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1802_SYNC_start_value }
                     };

/* index 0x1803 :   Transmit PDO 4 Parameter. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1803 = 6; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1803_COB_ID_used_by_PDO = 0x480;	/* 1152 */
                    UNS8 AnyId_Canopen_Client_obj1803_Transmission_Type = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1803_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1803_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 AnyId_Canopen_Client_obj1803_Event_Timer = 0x0;	/* 0 */
                    UNS8 AnyId_Canopen_Client_obj1803_SYNC_start_value = 0x0;	/* 0 */
                    ODCallback_t AnyId_Canopen_Client_Index1803_callbacks[] = 
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex AnyId_Canopen_Client_Index1803[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1803 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1803_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1803_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1803_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1803_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&AnyId_Canopen_Client_obj1803_Event_Timer },
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_obj1803_SYNC_start_value }
                     };

/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1A00[] = 
                    {
                      0x20000040,	/* 536870976 */
                      0x20010008,	/* 536936456 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_Canopen_Client_Index1A00[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A00[7] }
                     };

/* index 0x1A01 :   Transmit PDO 2 Mapping. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1A01 = 8; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1A01[] = 
                    {
                      0x20020008,	/* 537001992 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_Canopen_Client_Index1A01[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1A01 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A01[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A01[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A01[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A01[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A01[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A01[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A01[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A01[7] }
                     };

/* index 0x1A02 :   Transmit PDO 3 Mapping. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1A02 = 8; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1A02[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_Canopen_Client_Index1A02[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1A02 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A02[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A02[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A02[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A02[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A02[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A02[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A02[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A02[7] }
                     };

/* index 0x1A03 :   Transmit PDO 4 Mapping. */
                    UNS8 AnyId_Canopen_Client_highestSubIndex_obj1A03 = 8; /* number of subindex - 1*/
                    UNS32 AnyId_Canopen_Client_obj1A03[] = 
                    {
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0,	/* 0 */
                      0x0	/* 0 */
                    };
                    subindex AnyId_Canopen_Client_Index1A03[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AnyId_Canopen_Client_highestSubIndex_obj1A03 },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A03[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A03[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A03[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A03[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A03[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A03[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A03[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&AnyId_Canopen_Client_obj1A03[7] }
                     };

/* index 0x2000 :   Mapped variable Uid */
                    subindex AnyId_Canopen_Client_Index2000[] = 
                     {
                       { RW, uint64, sizeof (UNS64), (void*)&Uid }
                     };

/* index 0x2001 :   Mapped variable KeyValue */
                    subindex AnyId_Canopen_Client_Index2001[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&KeyValue }
                     };

/* index 0x2002 :   Mapped variable AddValue */
                    subindex AnyId_Canopen_Client_Index2002[] = 
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&AddValue }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable AnyId_Canopen_Client_objdict[] = 
{
  { (subindex*)AnyId_Canopen_Client_Index1000,sizeof(AnyId_Canopen_Client_Index1000)/sizeof(AnyId_Canopen_Client_Index1000[0]), 0x1000},
  { (subindex*)AnyId_Canopen_Client_Index1001,sizeof(AnyId_Canopen_Client_Index1001)/sizeof(AnyId_Canopen_Client_Index1001[0]), 0x1001},
  { (subindex*)AnyId_Canopen_Client_Index1003,sizeof(AnyId_Canopen_Client_Index1003)/sizeof(AnyId_Canopen_Client_Index1003[0]), 0x1003},
  { (subindex*)AnyId_Canopen_Client_Index1008,sizeof(AnyId_Canopen_Client_Index1008)/sizeof(AnyId_Canopen_Client_Index1008[0]), 0x1008},
  { (subindex*)AnyId_Canopen_Client_Index1009,sizeof(AnyId_Canopen_Client_Index1009)/sizeof(AnyId_Canopen_Client_Index1009[0]), 0x1009},
  { (subindex*)AnyId_Canopen_Client_Index100A,sizeof(AnyId_Canopen_Client_Index100A)/sizeof(AnyId_Canopen_Client_Index100A[0]), 0x100A},
  { (subindex*)AnyId_Canopen_Client_Index1011,sizeof(AnyId_Canopen_Client_Index1011)/sizeof(AnyId_Canopen_Client_Index1011[0]), 0x1011},
  { (subindex*)AnyId_Canopen_Client_Index1012,sizeof(AnyId_Canopen_Client_Index1012)/sizeof(AnyId_Canopen_Client_Index1012[0]), 0x1012},
  { (subindex*)AnyId_Canopen_Client_Index1013,sizeof(AnyId_Canopen_Client_Index1013)/sizeof(AnyId_Canopen_Client_Index1013[0]), 0x1013},
  { (subindex*)AnyId_Canopen_Client_Index1014,sizeof(AnyId_Canopen_Client_Index1014)/sizeof(AnyId_Canopen_Client_Index1014[0]), 0x1014},
  { (subindex*)AnyId_Canopen_Client_Index1015,sizeof(AnyId_Canopen_Client_Index1015)/sizeof(AnyId_Canopen_Client_Index1015[0]), 0x1015},
  { (subindex*)AnyId_Canopen_Client_Index1016,sizeof(AnyId_Canopen_Client_Index1016)/sizeof(AnyId_Canopen_Client_Index1016[0]), 0x1016},
  { (subindex*)AnyId_Canopen_Client_Index1017,sizeof(AnyId_Canopen_Client_Index1017)/sizeof(AnyId_Canopen_Client_Index1017[0]), 0x1017},
  { (subindex*)AnyId_Canopen_Client_Index1018,sizeof(AnyId_Canopen_Client_Index1018)/sizeof(AnyId_Canopen_Client_Index1018[0]), 0x1018},
  { (subindex*)AnyId_Canopen_Client_Index1200,sizeof(AnyId_Canopen_Client_Index1200)/sizeof(AnyId_Canopen_Client_Index1200[0]), 0x1200},
  { (subindex*)AnyId_Canopen_Client_Index1280,sizeof(AnyId_Canopen_Client_Index1280)/sizeof(AnyId_Canopen_Client_Index1280[0]), 0x1280},
  { (subindex*)AnyId_Canopen_Client_Index1281,sizeof(AnyId_Canopen_Client_Index1281)/sizeof(AnyId_Canopen_Client_Index1281[0]), 0x1281},
  { (subindex*)AnyId_Canopen_Client_Index1400,sizeof(AnyId_Canopen_Client_Index1400)/sizeof(AnyId_Canopen_Client_Index1400[0]), 0x1400},
  { (subindex*)AnyId_Canopen_Client_Index1401,sizeof(AnyId_Canopen_Client_Index1401)/sizeof(AnyId_Canopen_Client_Index1401[0]), 0x1401},
  { (subindex*)AnyId_Canopen_Client_Index1402,sizeof(AnyId_Canopen_Client_Index1402)/sizeof(AnyId_Canopen_Client_Index1402[0]), 0x1402},
  { (subindex*)AnyId_Canopen_Client_Index1403,sizeof(AnyId_Canopen_Client_Index1403)/sizeof(AnyId_Canopen_Client_Index1403[0]), 0x1403},
  { (subindex*)AnyId_Canopen_Client_Index1600,sizeof(AnyId_Canopen_Client_Index1600)/sizeof(AnyId_Canopen_Client_Index1600[0]), 0x1600},
  { (subindex*)AnyId_Canopen_Client_Index1601,sizeof(AnyId_Canopen_Client_Index1601)/sizeof(AnyId_Canopen_Client_Index1601[0]), 0x1601},
  { (subindex*)AnyId_Canopen_Client_Index1602,sizeof(AnyId_Canopen_Client_Index1602)/sizeof(AnyId_Canopen_Client_Index1602[0]), 0x1602},
  { (subindex*)AnyId_Canopen_Client_Index1603,sizeof(AnyId_Canopen_Client_Index1603)/sizeof(AnyId_Canopen_Client_Index1603[0]), 0x1603},
  { (subindex*)AnyId_Canopen_Client_Index1800,sizeof(AnyId_Canopen_Client_Index1800)/sizeof(AnyId_Canopen_Client_Index1800[0]), 0x1800},
  { (subindex*)AnyId_Canopen_Client_Index1801,sizeof(AnyId_Canopen_Client_Index1801)/sizeof(AnyId_Canopen_Client_Index1801[0]), 0x1801},
  { (subindex*)AnyId_Canopen_Client_Index1802,sizeof(AnyId_Canopen_Client_Index1802)/sizeof(AnyId_Canopen_Client_Index1802[0]), 0x1802},
  { (subindex*)AnyId_Canopen_Client_Index1803,sizeof(AnyId_Canopen_Client_Index1803)/sizeof(AnyId_Canopen_Client_Index1803[0]), 0x1803},
  { (subindex*)AnyId_Canopen_Client_Index1A00,sizeof(AnyId_Canopen_Client_Index1A00)/sizeof(AnyId_Canopen_Client_Index1A00[0]), 0x1A00},
  { (subindex*)AnyId_Canopen_Client_Index1A01,sizeof(AnyId_Canopen_Client_Index1A01)/sizeof(AnyId_Canopen_Client_Index1A01[0]), 0x1A01},
  { (subindex*)AnyId_Canopen_Client_Index1A02,sizeof(AnyId_Canopen_Client_Index1A02)/sizeof(AnyId_Canopen_Client_Index1A02[0]), 0x1A02},
  { (subindex*)AnyId_Canopen_Client_Index1A03,sizeof(AnyId_Canopen_Client_Index1A03)/sizeof(AnyId_Canopen_Client_Index1A03[0]), 0x1A03},
  { (subindex*)AnyId_Canopen_Client_Index2000,sizeof(AnyId_Canopen_Client_Index2000)/sizeof(AnyId_Canopen_Client_Index2000[0]), 0x2000},
  { (subindex*)AnyId_Canopen_Client_Index2001,sizeof(AnyId_Canopen_Client_Index2001)/sizeof(AnyId_Canopen_Client_Index2001[0]), 0x2001},
  { (subindex*)AnyId_Canopen_Client_Index2002,sizeof(AnyId_Canopen_Client_Index2002)/sizeof(AnyId_Canopen_Client_Index2002[0]), 0x2002},
};

const indextable * AnyId_Canopen_Client_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1003: i = 2;*callbacks = AnyId_Canopen_Client_Index1003_callbacks; break;
		case 0x1008: i = 3;break;
		case 0x1009: i = 4;break;
		case 0x100A: i = 5;break;
		case 0x1011: i = 6;break;
		case 0x1012: i = 7;break;
		case 0x1013: i = 8;break;
		case 0x1014: i = 9;break;
		case 0x1015: i = 10;break;
		case 0x1016: i = 11;break;
		case 0x1017: i = 12;*callbacks = AnyId_Canopen_Client_Index1017_callbacks; break;
		case 0x1018: i = 13;break;
		case 0x1200: i = 14;break;
		case 0x1280: i = 15;break;
		case 0x1281: i = 16;break;
		case 0x1400: i = 17;break;
		case 0x1401: i = 18;break;
		case 0x1402: i = 19;break;
		case 0x1403: i = 20;break;
		case 0x1600: i = 21;break;
		case 0x1601: i = 22;break;
		case 0x1602: i = 23;break;
		case 0x1603: i = 24;break;
		case 0x1800: i = 25;*callbacks = AnyId_Canopen_Client_Index1800_callbacks; break;
		case 0x1801: i = 26;*callbacks = AnyId_Canopen_Client_Index1801_callbacks; break;
		case 0x1802: i = 27;*callbacks = AnyId_Canopen_Client_Index1802_callbacks; break;
		case 0x1803: i = 28;*callbacks = AnyId_Canopen_Client_Index1803_callbacks; break;
		case 0x1A00: i = 29;break;
		case 0x1A01: i = 30;break;
		case 0x1A02: i = 31;break;
		case 0x1A03: i = 32;break;
		case 0x2000: i = 33;break;
		case 0x2001: i = 34;break;
		case 0x2002: i = 35;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &AnyId_Canopen_Client_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status AnyId_Canopen_Client_PDO_status[4] = {s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer,s_PDO_status_Initializer};

const quick_index AnyId_Canopen_Client_firstIndex = {
  14, /* SDO_SVR */
  15, /* SDO_CLT */
  17, /* PDO_RCV */
  21, /* PDO_RCV_MAP */
  25, /* PDO_TRS */
  29 /* PDO_TRS_MAP */
};

const quick_index AnyId_Canopen_Client_lastIndex = {
  14, /* SDO_SVR */
  16, /* SDO_CLT */
  20, /* PDO_RCV */
  24, /* PDO_RCV_MAP */
  28, /* PDO_TRS */
  32 /* PDO_TRS_MAP */
};

const UNS16 AnyId_Canopen_Client_ObjdictSize = sizeof(AnyId_Canopen_Client_objdict)/sizeof(AnyId_Canopen_Client_objdict[0]); 

CO_Data AnyId_Canopen_Client_Data = CANOPEN_NODE_DATA_INITIALIZER(AnyId_Canopen_Client);

